# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 959f14063575f49a2dcd2b2079472e21be7822fadc3800675d747acd836af9b31ba4b69bb1844a7e4e88938795668e15d61062b04f300c040aff79b7df902a9f

test:
  secret_key_base: 5499690da4aefee6fcbbfdc2597aa6580c9c8003f4a8d3a1dc66337dbebec1eb5d1de596fb1389818c021308f331739dadedeb0ce15330154e51c27760e35f68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
